In [1]:
%matplotlib tk
import matplotlib.pyplot as plt
import numpy as np

from PIL import Image

In [2]:
def get_input_box(im, min_points=10):
    """
    Allows user to input line segments; computes centers and directions.
    Inputs:
        im: np.ndarray of shape (height, width, 3)
        min_lines: minimum number of lines required
    Returns:
        n: number of lines from input
        lines: np.ndarray of shape (3, n)
            where each column denotes the parameters of the line equation
        centers: np.ndarray of shape (3, n)
            where each column denotes the homogeneous coordinates of the centers
    """
    n = 0
    lines = np.zeros((3, 0))
    centers = np.zeros((3, 0))

    plt.figure()
    plt.imshow(im)
    plt.show()
    print('Set at least %d lines to compute vanishing point' % min_points)
    x = []
    
    while True:
        print('Click the two endpoints, use the right key to undo, and use the middle key to stop input')
        clicked = plt.ginput(min_points, timeout=0, show_clicks=True)
        for clk in clicked:
            pt = np.array([clk[0], clk[1], 1])
            plt.plot([pt[0]-260, pt[0]+260], [pt[1]-260, pt[1]-260], color='b')
            plt.plot([pt[0]-260, pt[0]-260], [pt[1]-260, pt[1]+260], color='b')
            plt.plot([pt[0]+260, pt[0]+260], [pt[1]+260, pt[1]-260], color='b')
            plt.plot([pt[0]+260, pt[0]-260], [pt[1]+260, pt[1]+260], color='b')
            x.append(pt)
        break

    return x

In [3]:
im = np.asarray(Image.open('label.jpg'))

/home/hangzheng/anaconda3/envs/tf/lib/python3.7/site-packages/PIL/Image.py:3077: DecompressionBombWarning: Image size (102000000 pixels) exceeds limit of 89478485 pixels, could be decompression bomb DOS attack.
  DecompressionBombWarning,


In [4]:
pts = get_input_box(im,100)

Set at least 100 lines to compute vanishing point
Click the two endpoints, use the right key to undo, and use the middle key to stop input


In [19]:
import pprint
pprint.pprint(pts)

[array([705.10753319, 644.43046562,   1.        ]),
 array([1.74213202e+03, 6.07393877e+02, 1.00000000e+00]),
 array([2.70508333e+03, 6.93812584e+02, 1.00000000e+00]),
 array([3.65568910e+03, 7.80231291e+02, 1.00000000e+00]),
 array([4.66802253e+03, 7.43194702e+02, 1.00000000e+00]),
 array([5.55690066e+03, 7.80231291e+02, 1.00000000e+00]),
 array([6.53219750e+03, 9.28377646e+02, 1.00000000e+00]),
 array([7.61860410e+03, 8.29613409e+02, 1.00000000e+00]),
 array([8.64328306e+03, 9.03686587e+02, 1.00000000e+00]),
 array([9.54450672e+03, 9.40723176e+02, 1.00000000e+00]),
 array([6.55725415e+02, 1.58269071e+03, 1.00000000e+00]),
 array([1.64336778e+03, 1.61972730e+03, 1.00000000e+00]),
 array([2.60631909e+03, 1.66910942e+03, 1.00000000e+00]),
 array([3.61865252e+03, 1.70614601e+03, 1.00000000e+00]),
 array([4.61864041e+03, 1.66910942e+03, 1.00000000e+00]),
 array([5.56924619e+03, 1.71849154e+03, 1.00000000e+00]),
 array([6.53219750e+03, 1.86663789e+03, 1.00000000e+00]),
 array([7.58156751e+

In [24]:
pts_str = [str(f"{pt[0]} {pt[1]}\n") for pt in pts]
with open("cell_centers.txt", "w") as f:
    f.writelines(pts_str)

In [30]:
from matplotlib import image

for k, pt in enumerate(pts):
    for i in range(2):
        for j in range(2):
            patch = im[int(pt[1])-i*230:int(pt[1])-i*230+230,int(pt[0])-j*230:int(pt[0])-j*230+230]
            image.imsave(f"cells/{k*4+i*2+j}.jpg",patch)